### ISSUE TITLE
On each card, I should see a GitHub icon that takes me to the GitHub page for that resource

### ISSUE THREAD

**Issue by ibagha** [concourse/resource-types-website#102]
Acceptance Criteria
**Given I** am viewing a resource card
**I should** see a black octocat GitHub icon
**When I** click on the icon
**Then I** should be taken to the GitHub page for that resource

**_GitHub link styling_**
Icon should be available through GitHub website or design system
Height: 16px
Width: 16px

Link to Figma: https://www.figma.com/file/pmLRwbPKrwDAGn6XLDoUiA/Concourse-Resources?node-id=507%3A5

**Comment by ibagha** [comment]
Should we render this as an SVG so there are no sizing issues?

**Comment by ibagha** [comment]
Short term: Entire card should go to github page

**Comment by YoussB** [comment]
use the github icon set (elm github octicons)
