### ISSUE TITLE
Establish a metric for 'most popular'

### ISSUE THREAD

**Issue by ibagha** [concourse/resource-types-website#132]

**Comment by YoussB** [comment]
- number of docker pulls may be misleading. (Concourse polling docker)
- docker pulls number is inflated.
- how many pipelines have this resource enabled (would be done by using telemetry, which we don't have at the moment)
- verifying: high stars = high number of download.
- we'll get more accurate read on it after the 1st MVP.

- let's keep the github stars for the first MVP.

**Comment by YoussB** [comment]
x-posting comment from #65
https://github.com/concourse/dutyfree/issues/65#issuecomment-511219038.

also, will continue using github stars for the time being.
