### ISSUE TITLE
Notify maintainers to add resources to `concourse/resource-types`

### ISSUE THREAD

**Issue by YoussB** [concourse/resource-types-website#144]
- [x] create the `concourse/resource-types` repo.
- [x] add the current concourse maintained resources.
- [x] write-up a note to the current maintainers of the resources to add their resources to the repo.
- [x] send the note to the current maintainers and the community to submit their resources to the new repo.
- [ ] once the Beta is live, @vito to notify some folks on Discord to add their resources.

**Comment by YoussB** [comment]
- open an issue and @mention all the current contributors.
- what to do with the resources without response:
  - check the repo for activity and maybe open an issue on their repo.
  - if no response whatsoever just leave it!

**Comment by YoussB** [comment]
https://github.com/concourse/resource-types/pull/1

**Comment by YoussB** [comment]
- add a comment to the  resource types repo about deprecating the wiki.
- ping contributors on Discord, where possible.

**Comment by YoussB** [comment]
- after releasing, tell people again.

**Comment by vito** [comment]
I only really had one user in mind to ping on Discord, and I did that so I think this is done now!
