### ISSUE TITLE
I should see a footer on all pages with the specified styling and links

### ISSUE THREAD

**Issue by ibagha** [concourse/resource-types-website#155]
A/C

- [x] When I hover over the links, they should be underlined
- [x] When I click 'Terms of Use', I should be taken to the terms of use page
- [x] When I click 'Contribute' I should be taken to the Contribution readme 
- [x] When I click feedback, I should be taken to the github issues pages where I can submit feedback (https://github.com/concourse/dutyfree/issues/new)
- [ ] Styling should match mocks in Figma

Link to Figma: https://www.figma.com/file/pmLRwbPKrwDAGn6XLDoUiA/Concourse-Resources?node-id=1182%3A60

**Comment by jomsie** [comment]
for the underline, https://github.com/mdgriffith/elm-ui/issues/158

*sigh*

override time

**Comment by jomsie** [comment]
actually i might be able to do it with a very sharp shadow...

**Comment by jomsie** [comment]
for the actual terms of use page, some sort of routing needs to be set up... good reference:

https://elm.christmas/2018/15

**Comment by jomsie** [comment]
https://github.com/elm-explorations/test/issues/24
:(

previous tests which test the model changes are broken cause no testing for Browser / Nav.Key (which we use for changing the url)

time to ponder this

**Comment by ibagha** [comment]
> for the underline, [mdgriffith/elm-ui#158](https://github.com/mdgriffith/elm-ui/issues/158), won't be as easy as we'd hope
> 
> override time

The underline isn't necessary if there's no easy implementation. There are a number of other options (bold the text, darken the color of the text, or just keep as is with a changing tooltip on hover which should be built into the browser by default)

**Comment by jomsie** [comment]
@ibagha footer stuff should be up on the test site!
