### ISSUE TITLE
I should see a 'Terms of Use' page with the specified styling when I click 'Terms of Use' on the footer

### ISSUE THREAD

**Issue by ibagha** [concourse/resource-types-website#156]
A/C

- [ ] The content should have the specified padding above and below the text
- [ ] The content should fall onto the specified grid
- [ ] The content should match the content on the Figma page
- [ ] There should be a 'home' button with the specified styling that takes the user to the resource types homepage

Link to Figma: https://www.figma.com/file/pmLRwbPKrwDAGn6XLDoUiA/Concourse-Resources?node-id=1229%3A4

**Comment by jomsie** [comment]
@ibagha terms page should also be on test site :)
