### ISSUE TITLE
Update text sizes on card

### ISSUE THREAD

**Issue by YoussB** [concourse/resource-types-website#167]
Acceptance:
- [ ] make the resource type name: 16px
- [ ] make the resource type description: 14px
- [ ] falls on the 8pt grid as shown in the mock:
https://www.figma.com/file/pmLRwbPKrwDAGn6XLDoUiA/Concourse-Resources?node-id=508%3A0

**Comment by jomsie** [comment]
finished in https://github.com/concourse/resource-types-website/pull/168
