### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by schmurfy** [concourse/resource-types-website#243]
I have no access to posting on the forum yet and since it has been two days now I suppose it wasn't noticed.

**Comment by taylorsilva** [comment]
Thanks for letting us know! 

Side-node: the forum is being deprecated in favour of github discussions https://github.com/concourse/concourse/discussions
and you can always chat with us on discord for more real-time discussion https://concourse-ci.org/project.html

**Comment by jomsie** [comment]
Thanks for this @schmurfy, I've added a new issue [here](https://github.com/concourse/resource-types-website/issues/244).

I'll go ahead and close this for now, feel free to comment further with any more issues/details.

Thanks again! :)
