### ISSUE TITLE
The resources page should appear as a link on Concourse docs navigation

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/resource-types-website#37]

**Comment by ibagha** [comment]
The page will not be a separate website, it will be located in the navigation of the Concourse docs site

**Comment by jomsie** [comment]
we should investigate how items get added to the top bar, looks like a couple dupes:
https://github.com/concourse/docs/blob/master/html/top.tmpl
https://github.com/concourse/docs/blob/master/discourse/common/header.html
https://github.com/concourse/docs/blob/master/blog/default.hbs

side note: On the current docs site, the search bar is it's own little elm app: https://github.com/concourse/docs/tree/master/elm

**Comment by YoussB** [comment]
2 things:
- link on docs
- docs navigation in our app

**Comment by YoussB** [comment]
the link should have the text: "resource types"
