### ISSUE TITLE
I should not be able to see the text "All Resources" when I am on the duty Free home page or when I click on the All Resources catalog page

### ISSUE THREAD

**Issue by Pivotal-Kevin-Curley** [concourse/resource-types-website#49]
**As an** OSS Concourse User when I go to https://concourse.github.io/dutyfree/ 

**I can** not see the text "All Resources" when I am on the duty Free home page or when I click on the All Resources catalog page

**So that** I am not confused about what page I am on.

**Acceptance Criteria**
When I go to https://concourse.github.io/dutyfree/ 

**I do not see** the text "All Resources" when I am on the duty Free home page or when I click on the All Resources catalog page

**Comment by YoussB** [comment]
closing as we decided not to implement the categories.
