### ISSUE TITLE
I should see a banner on the homepage with a page title and a description

### ISSUE THREAD

**Issue by ibagha** [concourse/resource-types-website#82]
AC:
  - [ ] tested at different widths and not look blurry
  - [ ] the image is not slowing down the page.
  - [ ] test should say 'Concourse Resource Types' and subtext should say 'Find more things for your thing do-er to do'
  - [ ] the content should align with the 12 column grid and the 8px grid

**Comment by jomsie** [comment]
I think part of this story should be an investigation on how we want to serve assets (aka the background image).

I think concourse/concourse uses a [public folder](https://github.com/concourse/concourse/tree/master/web/public/images), and when it gets built it uses some neato [yarn calls here](https://github.com/concourse/concourse/blob/master/package.json), which also has it's own [custom index.html file](https://github.com/concourse/concourse/blob/master/web/public/index.html).

**Comment by ibagha** [comment]
@jomsie @YoussB Here are both the svg and the png for the updated banner. The banner is not designed to tile. The svg might be better for responsiveness, but feel free to play around and see what works better at different browser widths. 
[concourse-banner.zip](https://github.com/concourse/dutyfree/files/3986036/concourse-banner.zip)
