### ISSUE TITLE
I should see the resource name and description (if provided) on a card in the specified styling

### ISSUE THREAD

**Issue by ibagha** [concourse/resource-types-website#99]
**Resource name**
Font Family: Roboto Slab
Font Style: Regular
Font Size: 20px
Line Height: 26px
Line Height: 100%
Color: #2A2929
**Description**
Font Family: Barlow
Font Style: Regular
Font Size: 12px
Line Height: 14px
Line Height: 100%
Color: #5A5555

- This story will include the backend work needed in order to display the current resource types.

Acceptance criteria:
- [ ] The text should fall on the 8pt grid on the card
- [ ] the page should display the same resources as currently on the [concourse github wiki](https://github.com/concourse/concourse/wiki/Resource-Types)
- [ ] clicking on any resource card will take the user to the github page of the resource in the same window.

depends on #119 

Link to Figma: https://www.figma.com/file/pmLRwbPKrwDAGn6XLDoUiA/Concourse-Resources?node-id=507%3A5

**Comment by YoussB** [comment]
might also be a good idea to have this story as the first implementation story.

**Comment by zoetian** [comment]
Hey @jomsie, it seems like README is a little bit outdated. =)

**Comment by jomsie** [comment]
we don't have versions yet, i think, right @YoussB ? Is that a v2 feature?
